"""Curiosity — deciding what to wonder about, voicing tensions, pursuing impulses.

Curiosity is self-generated by evaluating the self-model, companion model,
contested beliefs, load-bearing observations, recurring goals, capability
needs, and meta-knowledge (Vision §16).  The impulse it raises is a
recommendation, not an action.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from jarvis.domain.enums.evidence_source import EvidenceSource
from jarvis.domain.enums.trigger_origin import TriggerOrigin
from jarvis.domain.services.curiosity import wonder
from jarvis.domain.services.goal_reflection import recurring_goals
from jarvis.domain.value_objects.confidence import Confidence
from jarvis.domain.value_objects.curiosity_impulse import CuriosityImpulse
from jarvis.domain.value_objects.evidence import Evidence
from jarvis.domain.value_objects.goal import Goal
from jarvis.executive.executive_controller import working_statement

if TYPE_CHECKING:
    from jarvis.domain.entities.belief import Belief
    from jarvis.domain.value_objects.reflection import Reflection
    from jarvis.jarvis import Jarvis


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_contested(belief: Belief) -> bool:
    """True when a belief carries both supporting and contradicting evidence
    *and* still leans neither way (confidence below the grounded threshold).
    """
    explanation = belief.explain()
    return bool(
        explanation.supporting
        and explanation.contradicting
        and belief.confidence.value < 0.5
    )


def _contested_working_belief(jarvis: Jarvis) -> Belief | None:
    """A working belief that is a live tension worth resolving (Vision §18)."""
    for belief in jarvis.beliefs.all_beliefs():
        if _is_contested(belief):
            return belief
    return None


def _unmined_load_bearing(jarvis: Jarvis) -> Reflection | None:
    """The top load-bearing observation not yet turned into a learned insight."""
    for finding in jarvis.reflect():
        if not _already_mined(jarvis, finding.observation):
            return finding
    return None


def _already_mined(jarvis: Jarvis, observation: str) -> bool:
    marker = f'"{observation}" is a common cause'
    return any(marker in belief.statement for belief in jarvis.beliefs.all_beliefs())


# ---------------------------------------------------------------------------
# Core curiosity functions
# ---------------------------------------------------------------------------


def feel_curious(jarvis: Jarvis) -> CuriosityImpulse | None:
    """Decide whether any known self-tendency is worth investigating (Vision §16).

    Considers Jarvis's whole self-model and raises an impulse for the most
    confident weakness worth acting on -- a recommendation, not an action, or
    None if nothing is confident enough (Vision §28).
    """
    from jarvis.domain.enums.capability_stance import CapabilityStance
    from jarvis.domain.services.capability_evaluator import recommend as recommend_capability

    by_confidence = sorted(
        jarvis.self_beliefs(), key=lambda belief: belief.confidence.value, reverse=True
    )
    for belief in by_confidence:
        impulse = wonder(belief)
        if impulse is not None:
            return impulse

    for belief in jarvis.companion.beliefs():
        explanation = belief.explain()
        if explanation.supporting and explanation.contradicting:
            return CuriosityImpulse(
                trigger=f"Find out whether my companion really: {belief.statement}",
                rationale=(
                    f'my belief that my companion "{belief.statement}" is contested'
                ),
                prompted_by_belief_id=belief.id,
            )

    contested = _contested_working_belief(jarvis)
    if contested is not None:
        topic = subject_of(contested.statement)
        return CuriosityImpulse(
            trigger=f"Resolve the tension in what I concluded about: {topic}",
            rationale=f'what I concluded about "{topic}" is contested by my evidence',
            prompted_by_belief_id=contested.id,
        )

    unmined = _unmined_load_bearing(jarvis)
    if unmined is not None:
        return CuriosityImpulse(
            trigger=f"Reflect on why several of my beliefs rest on: {unmined.observation}",
            rationale=(
                f'"{unmined.observation}" underpins {unmined.load} of my beliefs '
                "and I have not yet understood why"
            ),
            reflect_on=unmined.observation,
        )

    recurring = recurring_goals(jarvis.episodes.history())
    if recurring:
        for goal, count in recurring:
            if jarvis._is_open_stuck_goal(goal):
                part = jarvis._first_unreached_part(goal)
                if part is not None:
                    reached, known = jarvis.goal_progress(goal)
                    return CuriosityImpulse(
                        trigger=(
                            f"I've reached {reached} of {known} parts of {goal}; "
                            f"why can't I reach '{part}'?"
                        ),
                        rationale=(
                            f'the part "{part}" of goal "{goal}" is still unreached'
                        ),
                        goal=goal,
                    )
                return CuriosityImpulse(
                    trigger=f"Why do I keep returning to {goal} without reaching it?",
                    rationale=(
                        f'I have pursued the goal "{goal}" {count} times '
                        "without reaching it"
                    ),
                    goal=goal,
                )
        for goal, count in recurring:
            if not jarvis._is_exhausted_stuck_goal(goal):
                return CuriosityImpulse(
                    trigger=f"Why do I keep returning to: {goal}?",
                    rationale=f'I have pursued the goal "{goal}" {count} times',
                    goal=goal,
                )

    for need_statement, confidence in jarvis.capability_needs():
        if confidence.value < jarvis._knobs.insight_confidence:
            continue
        need = jarvis._needs.get_by_statement(need_statement)
        for capability in jarvis._capabilities.all_capabilities():
            if (
                recommend_capability(need, capability).stance
                is CapabilityStance.SUGGEST
            ):
                from jarvis.introspection import _NEED_PREFIX as _NEED_PREFIX_VAL
                subject = need_statement.removeprefix(_NEED_PREFIX_VAL)
                return CuriosityImpulse(
                    trigger=f"Acquire the capability to: {subject}",
                    rationale=(
                        f'I need "{subject}" (need confidence '
                        f"{confidence.value:.2f}) and do not have "
                        f"'{capability.name}' yet"
                    ),
                    capability_to_acquire=capability.name,
                )

    # Check meta-knowledge for reasoning strategy insights
    from jarvis.domain.services.meta_observation import observe_reasoning_effectiveness
    meta = observe_reasoning_effectiveness(jarvis.episodes.history())
    if meta is not None and meta.confidence.value >= 0.5:
        return CuriosityImpulse(
            trigger=f"Reflect on my reasoning strategy: {meta.statement}",
            rationale=(
                f'my meta-observation "{meta.statement}" has confidence '
                f"{meta.confidence.value:.2f}"
            ),
        )

    return None


def ask_about(jarvis: Jarvis, topic: str) -> str | None:
    """Voice an unresolved tension so the companion can settle it (Vision §18,
    §37), or None when Jarvis holds no contested belief about ``topic``.
    """
    belief = jarvis.beliefs.get_by_statement(working_statement(topic))
    if belief is None or not _is_contested(belief):
        return None
    explanation = belief.explain()
    for_it = explanation.supporting[0].content
    against_it = explanation.contradicting[0].content
    return (
        f'About "{topic}", I have heard both "{for_it}" and "{against_it}" — '
        "which is it?"
    )


def resolve(jarvis: Jarvis, topic: str, guidance: str, supports: bool = True) -> Belief | None:
    """Take the companion's guidance on a contested topic as evidence (Vision §18,
    §20), tipping the working belief toward one side -- derived, never set.
    """
    episode = jarvis.think(
        topic,
        evidence=[
            Evidence(
                content=guidance,
                source=EvidenceSource.USER_STATEMENT,
                weight=Confidence(1.0),
                supports=supports,
                context="companion guidance on a contested topic",
            )
        ],
    )
    return episode.working_belief


def pursue(jarvis: Jarvis, impulse: CuriosityImpulse):
    """Run a self-triggered episode for a curiosity impulse (Vision §16, §31)."""
    if impulse.reflect_on is not None:
        jarvis.reflect_cycle()
    if impulse.capability_to_acquire is not None:
        jarvis.acquire_capability(impulse.capability_to_acquire)
    goal = Goal(statement=impulse.goal) if impulse.goal is not None else None
    from jarvis.domain.aggregates.cognitive_episode import CognitiveEpisode
    episode = CognitiveEpisode(
        trigger=impulse.trigger, origin=TriggerOrigin.CURIOSITY, goal=goal
    )
    return jarvis._run(episode)


def subject_of(statement: str) -> str:
    """Best-effort extraction of the subject from a belief statement."""
    for prefix in ("I believe ", "My companion ", "I "):
        if statement.startswith(prefix):
            return statement[len(prefix):]
    return statement
