"""Curiosity — deciding what to wonder about, voicing tensions, pursuing impulses.

Curiosity is self-generated by evaluating the self-model, companion model,
contested beliefs, load-bearing observations, recurring goals, capability
needs, and meta-knowledge (Vision §16).  The impulse it raises is a
recommendation, not an action.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from jarvis.cognitive import run_episode
from jarvis.domain.enums.evidence_source import EvidenceSource
from jarvis.domain.enums.trigger_origin import TriggerOrigin
from jarvis.domain.repositories.belief_repository import resolve_belief_for
from jarvis.domain.services.attention_priority import (
    ATTEND_THRESHOLD,
    derive_attention_priorities,
)
from jarvis.domain.services.curiosity import wonder
from jarvis.domain.services.goal_reflection import recurring_goals
from jarvis.domain.value_objects.confidence import Confidence
from jarvis.domain.value_objects.curiosity_impulse import CuriosityImpulse
from jarvis.domain.value_objects.evidence import Evidence
from jarvis.domain.value_objects.goal import Goal
from jarvis.goals import (
    first_unreached_part,
    is_exhausted_stuck_goal,
    is_open_stuck_goal,
)

if TYPE_CHECKING:
    from jarvis.domain.entities.belief import Belief
    from jarvis.domain.value_objects.reflection import Reflection
    from jarvis.jarvis import Jarvis


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_contested(belief: Belief) -> bool:
    """True when a belief carries both supporting and contradicting evidence
    *and* still leans neither way (confidence below the grounded threshold).
    """
    explanation = belief.explain()
    return bool(
        explanation.supporting
        and explanation.contradicting
        and belief.confidence.value < 0.5
    )


def _contested_working_belief(jarvis: Jarvis) -> Belief | None:
    """A working belief that is a live tension worth resolving (Vision §18)."""
    for belief in jarvis.beliefs.all_beliefs():
        if _is_contested(belief):
            return belief
    return None


def _unmined_load_bearing(jarvis: Jarvis) -> Reflection | None:
    """The top load-bearing observation not yet turned into a learned insight."""
    for finding in jarvis.reflect():
        if not _already_mined(jarvis, finding.observation):
            return finding
    return None


def _already_mined(jarvis: Jarvis, observation: str) -> bool:
    marker = f'"{observation}" is a common cause'
    return any(marker in belief.statement for belief in jarvis.beliefs.all_beliefs())


# ---------------------------------------------------------------------------
# Core curiosity functions
# ---------------------------------------------------------------------------


def feel_curious(jarvis: Jarvis) -> CuriosityImpulse | None:
    """Decide whether any known self-tendency is worth investigating (Vision §16).

    Considers Jarvis's whole self-model and raises an impulse for the most
    confident weakness worth acting on -- a recommendation, not an action, or
    None if nothing is confident enough (Vision §28).
    """
    from jarvis.domain.enums.capability_stance import CapabilityStance
    from jarvis.domain.services.capability_evaluator import recommend as recommend_capability

    by_confidence = sorted(
        jarvis.self_beliefs(), key=lambda belief: belief.confidence.value, reverse=True
    )
    for belief in by_confidence:
        impulse = wonder(belief)
        if impulse is not None:
            return impulse

    for belief in jarvis.companion.beliefs():
        explanation = belief.explain()
        if explanation.supporting and explanation.contradicting:
            return CuriosityImpulse(
                trigger=f"Find out whether my companion really: {belief.statement}",
                rationale=(
                    f'my belief that my companion "{belief.statement}" is contested'
                ),
                prompted_by_belief_id=belief.id,
            )

    contested = _contested_working_belief(jarvis)
    if contested is not None:
        topic = subject_of(contested.statement)
        return CuriosityImpulse(
            trigger=f"Resolve the tension in what I concluded about: {topic}",
            rationale=f'what I concluded about "{topic}" is contested by my evidence',
            prompted_by_belief_id=contested.id,
        )

    unmined = _unmined_load_bearing(jarvis)
    if unmined is not None:
        return CuriosityImpulse(
            trigger=f"Reflect on why several of my beliefs rest on: {unmined.observation}",
            rationale=(
                f'"{unmined.observation}" underpins {unmined.load} of my beliefs '
                "and I have not yet understood why"
            ),
            reflect_on=unmined.observation,
        )

    recurring = recurring_goals(jarvis.episodes.history())
    if recurring:
        for goal, count in recurring:
            if is_open_stuck_goal(jarvis, goal):
                part = first_unreached_part(jarvis, goal)
                if part is not None:
                    reached, known = jarvis.goal_progress(goal)
                    return CuriosityImpulse(
                        trigger=(
                            f"I've reached {reached} of {known} parts of {goal}; "
                            f"why can't I reach '{part}'?"
                        ),
                        rationale=(
                            f'the part "{part}" of goal "{goal}" is still unreached'
                        ),
                        goal=goal,
                    )
                return CuriosityImpulse(
                    trigger=f"Why do I keep returning to {goal} without reaching it?",
                    rationale=(
                        f'I have pursued the goal "{goal}" {count} times '
                        "without reaching it"
                    ),
                    goal=goal,
                )
        for goal, count in recurring:
            if not is_exhausted_stuck_goal(jarvis, goal):
                return CuriosityImpulse(
                    trigger=f"Why do I keep returning to: {goal}?",
                    rationale=f'I have pursued the goal "{goal}" {count} times',
                    goal=goal,
                )

    for need_statement, confidence in jarvis.capability_needs():
        if confidence.value < jarvis.knobs().insight_confidence:
            continue
        need = jarvis.needs.get_by_statement(need_statement)
        for capability in jarvis.capability_store.all_capabilities():
            if (
                recommend_capability(need, capability).stance
                is CapabilityStance.SUGGEST
            ):
                from jarvis.capabilities import NEED_PREFIX
                subject = need_statement.removeprefix(NEED_PREFIX)
                return CuriosityImpulse(
                    trigger=f"Acquire the capability to: {subject}",
                    rationale=(
                        f'I need "{subject}" (need confidence '
                        f"{confidence.value:.2f}) and do not have "
                        f"'{capability.name}' yet"
                    ),
                    capability_to_acquire=capability.name,
                )

    # Check meta-knowledge for reasoning strategy insights
    from jarvis.domain.services.meta_observation import observe_reasoning_effectiveness
    meta = observe_reasoning_effectiveness(jarvis.episodes.history())
    if meta is not None and meta.confidence.value >= 0.5:
        return CuriosityImpulse(
            trigger=f"Reflect on my reasoning strategy: {meta.statement}",
            rationale=(
                f'my meta-observation "{meta.statement}" has confidence '
                f"{meta.confidence.value:.2f}"
            ),
        )

    # Check for destabilizing temporal patterns (Phase 10)
    from jarvis.domain.services.temporal_reasoning import TemporalPattern, detect_pattern
    # Collect unique subjects from episode history
    history = jarvis.episodes.history()
    seen_subjects: set[str] = set()
    for record in history:
        subject = record.trigger
        if subject in seen_subjects:
            continue
        seen_subjects.add(subject)
        pattern = detect_pattern(subject, history)
        if pattern is not None and pattern.pattern in (
            TemporalPattern.OSCILLATING,
            TemporalPattern.RECURRING_CONTRADICTION,
        ):
            return CuriosityImpulse(
                trigger=f"Investigate unstable belief: {subject}",
                rationale=pattern.description,
            )

    # Open questions are attention candidates too (unresolved lifecycle): when
    # nothing evidence-derived wins above, the oldest open question is worth
    # investigating. Without any noted questions this changes nothing.
    open_questions = jarvis.open_questions()
    if open_questions:
        oldest = open_questions[0]
        return CuriosityImpulse(
            trigger=f"Investigate the open question: {oldest.question}",
            rationale=(
                f'"{oldest.question}" has been open since '
                f"{oldest.opened_at.date().isoformat()} without an answer"
            ),
        )

    return None


def wake(jarvis: Jarvis) -> CuriosityImpulse | None:
    """Propose attending to the single most salient topic from experience.

    Unlike :func:`feel_curious` -- whose cascade stages are a static class order
    (audit §2.2) -- ``wake`` re-ranks the whole recent history by derived saliency:
    the topic Jarvis keeps returning to, keeps failing to settle, or keeps
    revising scores highest.  That is "what to attend to next" *learned from past
    episodes*: a fresh Jarvis wakes to nothing, an experienced one wakes to what
    it has most left open (Vision §16).  Nothing is mutated; the ranking is
    re-derived per call and reversible.
    """
    priorities = derive_attention_priorities(jarvis.episodes.history())
    if not priorities:
        return None
    top = priorities[0]
    if top.priority < ATTEND_THRESHOLD:
        return None
    open_note = f", {top.unresolved} still open" if top.unresolved else ""
    revision_note = " and still changing" if top.revised else ""
    return CuriosityImpulse(
        trigger=f"Attend to what I keep leaving open: {top.representative}",
        rationale=(
            f'"{top.topic}" recurs {top.episodes_on_topic} time(s) in my recent '
            f"history{open_note}{revision_note} -- it ranks {top.priority:.2f} "
            "on my attention"
        ),
        target_topic_id=top.topic,
        representative_trigger=top.representative,
    )


def ask_about(jarvis: Jarvis, topic: str) -> str | None:
    """Voice an unresolved tension so the companion can settle it (Vision §18,
    §37), or None when Jarvis holds no contested belief about ``topic``.
    """
    belief = resolve_belief_for(jarvis.beliefs, topic)
    if belief is None or not _is_contested(belief):
        return None
    explanation = belief.explain()
    for_it = explanation.supporting[0].content
    against_it = explanation.contradicting[0].content
    return (
        f'About "{topic}", I have heard both "{for_it}" and "{against_it}" — '
        "which is it?"
    )


def resolve(jarvis: Jarvis, topic: str, guidance: str, supports: bool = True) -> Belief | None:
    """Take the companion's guidance on a contested topic as evidence (Vision §18,
    §20), tipping the working belief toward one side -- derived, never set.
    """
    episode = jarvis.think(
        topic,
        evidence=[
            Evidence(
                content=guidance,
                source=EvidenceSource.USER_STATEMENT,
                weight=Confidence(1.0),
                supports=supports,
                context="companion guidance on a contested topic",
            )
        ],
    )
    return episode.working_belief


def pursue(jarvis: Jarvis, impulse: CuriosityImpulse):
    """Run a self-triggered episode for a curiosity impulse (Vision §16, §31)."""
    if impulse.reflect_on is not None:
        jarvis.reflect_cycle()
    if impulse.capability_to_acquire is not None:
        jarvis.acquire_capability(impulse.capability_to_acquire)
    goal = Goal(statement=impulse.goal) if impulse.goal is not None else None
    from jarvis.domain.aggregates.cognitive_episode import CognitiveEpisode
    # A wake() impulse carries the *real* trigger of the selected topic (its
    # representative) so the episode records an actual experience, not a
    # narration; its canonical topic identity travels with the episode so
    # curiosity provenance survives persistence.
    trigger = impulse.representative_trigger or impulse.trigger
    episode = CognitiveEpisode(
        trigger=trigger,
        origin=TriggerOrigin.CURIOSITY,
        goal=goal,
        target_topic_id=impulse.target_topic_id,
    )
    return run_episode(jarvis, episode)


def subject_of(statement: str) -> str:
    """Best-effort extraction of the subject from a belief statement."""
    for prefix in ("I believe ", "My companion ", "I "):
        if statement.startswith(prefix):
            return statement[len(prefix):]
    return statement


# Public aliases so the Jarvis facade can import the helpers without the
# pyright reportPrivateUsage rule firing on cross-module underscore imports.
is_contested = _is_contested
contested_working_belief = _contested_working_belief
